name: Ephread
markdown: kramdown
exclude:
  - 'node_modules'
  - 'CNAME'
  - 'Gemfile.lock'
  - 'Gemfile'
  - 'Gulpfile.babel.js'
  - 'package.json'
  - 'UNLICENSE'
  - 'README.md'
  - 'assets/javascripts/application.js.map'
  - 'assets/stylesheets/application.css.map'
  - 'assets/src/'

permalink: /articles/:year/:month/:day/:title/

plugins:
- jekyll-sitemap
